// Copyright IBM Corp. 2021, 2026
// SPDX-License-Identifier: MPL-2.0

package workmailuser

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktn/provider-aws.workmailUser.WorkmailUser",
		reflect.TypeOf((*WorkmailUser)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "city", GoGetter: "City"},
			_jsii_.MemberProperty{JsiiProperty: "cityInput", GoGetter: "CityInput"},
			_jsii_.MemberProperty{JsiiProperty: "company", GoGetter: "Company"},
			_jsii_.MemberProperty{JsiiProperty: "companyInput", GoGetter: "CompanyInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "country", GoGetter: "Country"},
			_jsii_.MemberProperty{JsiiProperty: "countryInput", GoGetter: "CountryInput"},
			_jsii_.MemberProperty{JsiiProperty: "department", GoGetter: "Department"},
			_jsii_.MemberProperty{JsiiProperty: "departmentInput", GoGetter: "DepartmentInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disabledDate", GoGetter: "DisabledDate"},
			_jsii_.MemberProperty{JsiiProperty: "displayName", GoGetter: "DisplayName"},
			_jsii_.MemberProperty{JsiiProperty: "displayNameInput", GoGetter: "DisplayNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "email", GoGetter: "Email"},
			_jsii_.MemberProperty{JsiiProperty: "emailInput", GoGetter: "EmailInput"},
			_jsii_.MemberProperty{JsiiProperty: "enabledDate", GoGetter: "EnabledDate"},
			_jsii_.MemberProperty{JsiiProperty: "firstName", GoGetter: "FirstName"},
			_jsii_.MemberProperty{JsiiProperty: "firstNameInput", GoGetter: "FirstNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "hiddenFromGlobalAddressList", GoGetter: "HiddenFromGlobalAddressList"},
			_jsii_.MemberProperty{JsiiProperty: "hiddenFromGlobalAddressListInput", GoGetter: "HiddenFromGlobalAddressListInput"},
			_jsii_.MemberProperty{JsiiProperty: "identityProviderIdentityStoreId", GoGetter: "IdentityProviderIdentityStoreId"},
			_jsii_.MemberProperty{JsiiProperty: "identityProviderUserId", GoGetter: "IdentityProviderUserId"},
			_jsii_.MemberProperty{JsiiProperty: "identityProviderUserIdInput", GoGetter: "IdentityProviderUserIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "initials", GoGetter: "Initials"},
			_jsii_.MemberProperty{JsiiProperty: "initialsInput", GoGetter: "InitialsInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jobTitle", GoGetter: "JobTitle"},
			_jsii_.MemberProperty{JsiiProperty: "jobTitleInput", GoGetter: "JobTitleInput"},
			_jsii_.MemberProperty{JsiiProperty: "lastName", GoGetter: "LastName"},
			_jsii_.MemberProperty{JsiiProperty: "lastNameInput", GoGetter: "LastNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "mailboxDeprovisionedDate", GoGetter: "MailboxDeprovisionedDate"},
			_jsii_.MemberProperty{JsiiProperty: "mailboxProvisionedDate", GoGetter: "MailboxProvisionedDate"},
			_jsii_.MemberMethod{JsiiMethod: "markWriteOnlyAttribute", GoMethod: "MarkWriteOnlyAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "office", GoGetter: "Office"},
			_jsii_.MemberProperty{JsiiProperty: "officeInput", GoGetter: "OfficeInput"},
			_jsii_.MemberProperty{JsiiProperty: "organizationId", GoGetter: "OrganizationId"},
			_jsii_.MemberProperty{JsiiProperty: "organizationIdInput", GoGetter: "OrganizationIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "password", GoGetter: "Password"},
			_jsii_.MemberProperty{JsiiProperty: "passwordInput", GoGetter: "PasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberMethod{JsiiMethod: "registerProviderFeatureUsage", GoMethod: "RegisterProviderFeatureUsage"},
			_jsii_.MemberMethod{JsiiMethod: "resetCity", GoMethod: "ResetCity"},
			_jsii_.MemberMethod{JsiiMethod: "resetCompany", GoMethod: "ResetCompany"},
			_jsii_.MemberMethod{JsiiMethod: "resetCountry", GoMethod: "ResetCountry"},
			_jsii_.MemberMethod{JsiiMethod: "resetDepartment", GoMethod: "ResetDepartment"},
			_jsii_.MemberMethod{JsiiMethod: "resetFirstName", GoMethod: "ResetFirstName"},
			_jsii_.MemberMethod{JsiiMethod: "resetHiddenFromGlobalAddressList", GoMethod: "ResetHiddenFromGlobalAddressList"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdentityProviderUserId", GoMethod: "ResetIdentityProviderUserId"},
			_jsii_.MemberMethod{JsiiMethod: "resetInitials", GoMethod: "ResetInitials"},
			_jsii_.MemberMethod{JsiiMethod: "resetJobTitle", GoMethod: "ResetJobTitle"},
			_jsii_.MemberMethod{JsiiMethod: "resetLastName", GoMethod: "ResetLastName"},
			_jsii_.MemberMethod{JsiiMethod: "resetOffice", GoMethod: "ResetOffice"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPassword", GoMethod: "ResetPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetStreet", GoMethod: "ResetStreet"},
			_jsii_.MemberMethod{JsiiMethod: "resetTelephone", GoMethod: "ResetTelephone"},
			_jsii_.MemberMethod{JsiiMethod: "resetUserRole", GoMethod: "ResetUserRole"},
			_jsii_.MemberMethod{JsiiMethod: "resetZipCode", GoMethod: "ResetZipCode"},
			_jsii_.MemberProperty{JsiiProperty: "state", GoGetter: "State"},
			_jsii_.MemberProperty{JsiiProperty: "street", GoGetter: "Street"},
			_jsii_.MemberProperty{JsiiProperty: "streetInput", GoGetter: "StreetInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "telephone", GoGetter: "Telephone"},
			_jsii_.MemberProperty{JsiiProperty: "telephoneInput", GoGetter: "TelephoneInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "userId", GoGetter: "UserId"},
			_jsii_.MemberProperty{JsiiProperty: "userRole", GoGetter: "UserRole"},
			_jsii_.MemberProperty{JsiiProperty: "userRoleInput", GoGetter: "UserRoleInput"},
			_jsii_.MemberMethod{JsiiMethod: "with", GoMethod: "With"},
			_jsii_.MemberProperty{JsiiProperty: "zipCode", GoGetter: "ZipCode"},
			_jsii_.MemberProperty{JsiiProperty: "zipCodeInput", GoGetter: "ZipCodeInput"},
		},
		func() interface{} {
			j := jsiiProxy_WorkmailUser{}
			_jsii_.InitJsiiProxy(&j.Type__cdktnTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktn/provider-aws.workmailUser.WorkmailUserConfig",
		reflect.TypeOf((*WorkmailUserConfig)(nil)).Elem(),
	)
}
